from datetime import datetime, date
from sqlalchemy import Boolean, Date, DateTime, Float, ForeignKey, Index, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.base import Base

def now(): return datetime.utcnow()
class Channel(Base):
 __tablename__='channels'
 channel_id: Mapped[str]=mapped_column(String(64),primary_key=True); channel_url: Mapped[str|None]=mapped_column(String(500)); channel_handle: Mapped[str|None]=mapped_column(String(255)); channel_name: Mapped[str]=mapped_column(String(255)); description: Mapped[str|None]=mapped_column(Text); custom_url: Mapped[str|None]=mapped_column(String(500)); published_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); country: Mapped[str|None]=mapped_column(String(8)); default_language: Mapped[str|None]=mapped_column(String(32)); thumbnails: Mapped[dict]=mapped_column(JSON,default=dict); uploads_playlist_id: Mapped[str|None]=mapped_column(String(128)); subscriber_count: Mapped[int|None]=mapped_column(Integer); view_count: Mapped[int|None]=mapped_column(Integer); video_count: Mapped[int|None]=mapped_column(Integer); hidden_subscriber_count: Mapped[bool]=mapped_column(Boolean,default=False); is_own: Mapped[bool]=mapped_column(Boolean,default=False); last_fetched_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class Video(Base):
 __tablename__='videos'; __table_args__=(Index('ix_videos_channel_published','channel_id','published_at'),Index('ix_videos_format','format_classification'))
 video_id: Mapped[str]=mapped_column(String(32),primary_key=True); channel_id: Mapped[str]=mapped_column(ForeignKey('channels.channel_id'),index=True); title: Mapped[str]=mapped_column(String(500)); description: Mapped[str|None]=mapped_column(Text); published_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True); api_updated_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); duration_seconds: Mapped[int|None]=mapped_column(Integer); category_id: Mapped[str|None]=mapped_column(String(32)); default_language: Mapped[str|None]=mapped_column(String(32)); tags: Mapped[list]=mapped_column(JSON,default=list); thumbnails: Mapped[dict]=mapped_column(JSON,default=dict); live_broadcast_content: Mapped[str|None]=mapped_column(String(32)); privacy_status: Mapped[str|None]=mapped_column(String(32)); embeddable: Mapped[bool|None]=mapped_column(Boolean); made_for_kids: Mapped[bool|None]=mapped_column(Boolean); self_declared_made_for_kids: Mapped[bool|None]=mapped_column(Boolean); view_count: Mapped[int]=mapped_column(Integer,default=0); like_count: Mapped[int|None]=mapped_column(Integer); comment_count: Mapped[int|None]=mapped_column(Integer); video_url: Mapped[str]=mapped_column(String(500)); is_short: Mapped[bool]=mapped_column(Boolean,default=False); is_long_form: Mapped[bool]=mapped_column(Boolean,default=False); is_live: Mapped[bool]=mapped_column(Boolean,default=False); format_classification: Mapped[str]=mapped_column(String(32),default='unknown'); classification_confidence: Mapped[float]=mapped_column(Float,default=0); classification_reason: Mapped[str]=mapped_column(Text,default='Insufficient public metadata'); last_fetched_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class VideoSnapshot(Base):
 __tablename__='video_statistics_snapshots'; __table_args__=(UniqueConstraint('video_id','snapshot_timestamp',name='uq_video_snapshot'),Index('ix_video_snapshot_time','video_id','snapshot_timestamp'))
 id: Mapped[int]=mapped_column(primary_key=True); video_id: Mapped[str]=mapped_column(ForeignKey('videos.video_id'),index=True); snapshot_timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); view_count: Mapped[int]=mapped_column(Integer); like_count: Mapped[int|None]=mapped_column(Integer); comment_count: Mapped[int|None]=mapped_column(Integer); source: Mapped[str]=mapped_column(String(64),default='youtube_data_api'); raw_response_id: Mapped[int|None]=mapped_column(Integer)
class ChannelSnapshot(Base):
 __tablename__='channel_statistics_snapshots'; __table_args__=(UniqueConstraint('channel_id','snapshot_timestamp',name='uq_channel_snapshot'),)
 id: Mapped[int]=mapped_column(primary_key=True); channel_id: Mapped[str]=mapped_column(ForeignKey('channels.channel_id'),index=True); snapshot_timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); subscriber_count: Mapped[int|None]=mapped_column(Integer); view_count: Mapped[int|None]=mapped_column(Integer); video_count: Mapped[int|None]=mapped_column(Integer); source: Mapped[str]=mapped_column(String(64),default='youtube_data_api')
class DerivedVideoFeature(Base):
 __tablename__='derived_video_features'; video_id: Mapped[str]=mapped_column(ForeignKey('videos.video_id'),primary_key=True); topic: Mapped[str|None]=mapped_column(String(128),index=True); subtopic: Mapped[str|None]=mapped_column(String(128)); location: Mapped[str|None]=mapped_column(String(128)); features: Mapped[dict]=mapped_column(JSON,default=dict); local_performance_index: Mapped[float|None]=mapped_column(Float); provenance: Mapped[str]=mapped_column(String(32),default='DERIVED'); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class CompetitorChannel(Base):
 __tablename__='competitor_channels'; channel_id: Mapped[str]=mapped_column(ForeignKey('channels.channel_id'),primary_key=True); added_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); label: Mapped[str|None]=mapped_column(String(255)); public_data_only: Mapped[bool]=mapped_column(Boolean,default=True)
class Alert(Base):
 __tablename__='alerts'; __table_args__=(UniqueConstraint('dedupe_key',name='uq_alert_dedupe'),Index('ix_alert_status','status'))
 id: Mapped[int]=mapped_column(primary_key=True); alert_type: Mapped[str]=mapped_column(String(64)); status: Mapped[str]=mapped_column(String(32),default='open'); channel_id: Mapped[str|None]=mapped_column(String(64),index=True); video_id: Mapped[str|None]=mapped_column(String(32)); message: Mapped[str]=mapped_column(Text); details: Mapped[dict]=mapped_column(JSON,default=dict); dedupe_key: Mapped[str]=mapped_column(String(255)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class IngestionRun(Base):
 __tablename__='ingestion_runs'; id: Mapped[int]=mapped_column(primary_key=True); job_name: Mapped[str]=mapped_column(String(64),index=True); channel_id: Mapped[str|None]=mapped_column(String(64)); status: Mapped[str]=mapped_column(String(32),default='running'); started_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); finished_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); records_found: Mapped[int]=mapped_column(Integer,default=0); records_inserted: Mapped[int]=mapped_column(Integer,default=0); records_updated: Mapped[int]=mapped_column(Integer,default=0); error: Mapped[str|None]=mapped_column(Text)
class ApiRequest(Base):
 __tablename__='api_requests'; id: Mapped[int]=mapped_column(primary_key=True); requested_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); endpoint: Mapped[str]=mapped_column(String(128)); status_code: Mapped[int|None]=mapped_column(Integer); quota_cost: Mapped[int]=mapped_column(Integer,default=0); retries: Mapped[int]=mapped_column(Integer,default=0); error: Mapped[str|None]=mapped_column(Text)
class RawApiResponse(Base):
 __tablename__='raw_api_responses'; id: Mapped[int]=mapped_column(primary_key=True); source: Mapped[str]=mapped_column(String(64)); endpoint: Mapped[str]=mapped_column(String(128)); retrieved_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); payload: Mapped[dict]=mapped_column(JSON)
class OAuthCredentialMetadata(Base):
 __tablename__='oauth_credentials_metadata'; id: Mapped[int]=mapped_column(primary_key=True); channel_id: Mapped[str|None]=mapped_column(String(64)); status: Mapped[str]=mapped_column(String(32)); scopes: Mapped[list]=mapped_column(JSON,default=list); expires_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); last_synced_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); token_path: Mapped[str|None]=mapped_column(String(500))
